version: '3.4'

services:
  sme.serap.boletim.api:
    image: ${DOCKER_REGISTRY-}smeserapboletimapi
    build:
      context: .
      dockerfile: SME.SERAp.Boletim.Api/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sme-network

networks:
  sme-network:
    external:
      name: sme-network
    driver: bridge